
# Gem::Specification for Genitor-0.5.0
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{genitor}
  s.version = "0.5.0"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew King"]
  s.date = %q{2008-05-12}
  s.description = %q{Generation and updation of projects from templates.  Rake-powered, for sustainable blah blah.}
  s.email = %q{automatthew@gmail.com}
  s.files = ["CHANGELOG", "lib/genitor/polite_file.rb", "lib/genitor.rb", "LICENSE", "Manifest", "README", "test/helper.rb", "test/test_genitor.rb", "test/test_polite_file.rb", "test/testdata/app/alpha/beta/five.erb", "test/testdata/app/four.erb", "test/testdata/app/one", "test/testdata/app/six.textile", "test/testdata/app/three.rb", "test/testdata/app/two.txt", "genitor.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{genitor}
  s.rubygems_version = %q{1.1.1}
  s.summary = %q{Generation and updation of projects from templates.  Rake-powered, for sustainable blah blah.}
  s.test_files = ["test/test_genitor.rb", "test/test_polite_file.rb"]

  s.add_dependency(%q<rake>, [">= 0"])
  s.add_dependency(%q<erubis>, [">= 0"])
end


# # Original Rakefile source (requires the Echoe gem):
# 
# %w{rubygems}.each do |dep|
#   require dep
# end
# 
# Version = '0.5.0'
# 
# task :default => [:test]
# 
# begin
#   gem 'echoe', '>=2.7'
#   require 'echoe'
#   Echoe.new('genitor', Version) do |p|
#     p.project = 'genitor'
#     p.summary = "Generation and updation of projects from templates.  Rake-powered, for sustainable blah blah."
#     p.author = "Matthew King"
#     p.email = "automatthew@gmail.com"
#     p.ignore_pattern = /^(\.git).+/
#     p.test_pattern = "test/test_*.rb"
#     p.dependencies << "rake"
#     p.dependencies << "erubis"
#   end
# rescue
#   "(ignored echoe gemification, as you don't have the Right Stuff)"
# end
